//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blish_HUD.Strings.GameServices {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GraphicsService {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GraphicsService() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Blish_HUD.Strings.GameServices.GraphicsService", typeof(GraphicsService).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Graphics Settings 的當地語系化字串。
        /// </summary>
        internal static string GraphicsSettingsSection {
            get {
                return ResourceManager.GetString("GraphicsSettingsSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Enables additional scaling of the UI according to your system settings. 的當地語系化字串。
        /// </summary>
        internal static string Setting_DPIScaling_Description {
            get {
                return ResourceManager.GetString("Setting_DPIScaling_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 DPI Scaling 的當地語系化字串。
        /// </summary>
        internal static string Setting_DPIScaling_DisplayName {
            get {
                return ResourceManager.GetString("Setting_DPIScaling_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Disabled - Never Scale 的當地語系化字串。
        /// </summary>
        internal static string Setting_DPIScaling_NoScaling {
            get {
                return ResourceManager.GetString("Setting_DPIScaling_NoScaling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Automatic - Sync With Game 的當地語系化字串。
        /// </summary>
        internal static string Setting_DPIScaling_SyncWithGame {
            get {
                return ResourceManager.GetString("Setting_DPIScaling_SyncWithGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Enabled - Use Game DPI 的當地語系化字串。
        /// </summary>
        internal static string Setting_DPIScaling_UseGameDpi {
            get {
                return ResourceManager.GetString("Setting_DPIScaling_UseGameDpi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The method used to determine the framerate that Blish HUD should run at. 的當地語系化字串。
        /// </summary>
        internal static string Setting_FramerateLimiter_Description {
            get {
                return ResourceManager.GetString("Setting_FramerateLimiter_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Frame Limiter 的當地語系化字串。
        /// </summary>
        internal static string Setting_FramerateLimiter_DisplayName {
            get {
                return ResourceManager.GetString("Setting_FramerateLimiter_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 (Disabled because Blish HUD was started with --maxfps/--unlockfps specified) 的當地語系化字串。
        /// </summary>
        internal static string Setting_FramerateLimiter_Locked_Description {
            get {
                return ResourceManager.GetString("Setting_FramerateLimiter_Locked_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Locked To 30 Fps 的當地語系化字串。
        /// </summary>
        internal static string Setting_FramerateLimiter_LockedTo30Fps {
            get {
                return ResourceManager.GetString("Setting_FramerateLimiter_LockedTo30Fps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Locked To 60 Fps 的當地語系化字串。
        /// </summary>
        internal static string Setting_FramerateLimiter_LockedTo60Fps {
            get {
                return ResourceManager.GetString("Setting_FramerateLimiter_LockedTo60Fps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Locked To 90 Fps 的當地語系化字串。
        /// </summary>
        internal static string Setting_FramerateLimiter_LockedTo90Fps {
            get {
                return ResourceManager.GetString("Setting_FramerateLimiter_LockedTo90Fps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Match Monitor Refresh Rate 的當地語系化字串。
        /// </summary>
        internal static string Setting_FramerateLimiter_Unlimited {
            get {
                return ResourceManager.GetString("Setting_FramerateLimiter_Unlimited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 If enabled, the character position is smoothed to prevent 3D overlay elements from jumping around. 的當地語系化字串。
        /// </summary>
        internal static string Setting_SmoothCharacterPosition_Description {
            get {
                return ResourceManager.GetString("Setting_SmoothCharacterPosition_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Smooth Character Position 的當地語系化字串。
        /// </summary>
        internal static string Setting_SmoothCharacterPosition_DisplayName {
            get {
                return ResourceManager.GetString("Setting_SmoothCharacterPosition_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Determines the scaling of the UI. Either sync with game or set manually.
        ///NOTE: &apos;Automatic&apos; will only update while logged in with a character 的當地語系化字串。
        /// </summary>
        internal static string Setting_UIScaling_Description {
            get {
                return ResourceManager.GetString("Setting_UIScaling_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Interface Size 的當地語系化字串。
        /// </summary>
        internal static string Setting_UIScaling_DisplayName {
            get {
                return ResourceManager.GetString("Setting_UIScaling_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Large 的當地語系化字串。
        /// </summary>
        internal static string Setting_UIScaling_Large {
            get {
                return ResourceManager.GetString("Setting_UIScaling_Large", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Larger 的當地語系化字串。
        /// </summary>
        internal static string Setting_UIScaling_Larger {
            get {
                return ResourceManager.GetString("Setting_UIScaling_Larger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Normal 的當地語系化字串。
        /// </summary>
        internal static string Setting_UIScaling_Normal {
            get {
                return ResourceManager.GetString("Setting_UIScaling_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Small 的當地語系化字串。
        /// </summary>
        internal static string Setting_UIScaling_Small {
            get {
                return ResourceManager.GetString("Setting_UIScaling_Small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Automatic - Sync With Game 的當地語系化字串。
        /// </summary>
        internal static string Setting_UIScaling_SyncWithGame {
            get {
                return ResourceManager.GetString("Setting_UIScaling_SyncWithGame", resourceCulture);
            }
        }
    }
}
