//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blish_HUD.Strings.GameServices {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Gw2ApiService {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Gw2ApiService() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Blish_HUD.Strings.GameServices.Gw2ApiService", typeof(Gw2ApiService).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Character 的當地語系化字串。
        /// </summary>
        internal static string AccountInfo_Character {
            get {
                return ResourceManager.GetString("AccountInfo_Character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Commander 的當地語系化字串。
        /// </summary>
        internal static string AccountInfo_Commander {
            get {
                return ResourceManager.GetString("AccountInfo_Commander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Navigate to the official applications page. 的當地語系化字串。
        /// </summary>
        internal static string CreateTokenInstructions_Step1 {
            get {
                return ResourceManager.GetString("CreateTokenInstructions_Step1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Click &quot;New Key&quot;. 的當地語系化字串。
        /// </summary>
        internal static string CreateTokenInstructions_Step2 {
            get {
                return ResourceManager.GetString("CreateTokenInstructions_Step2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Select all permissions and press the
        ///&quot;CREATE API KEY&quot; button. 的當地語系化字串。
        /// </summary>
        internal static string CreateTokenInstructions_Step3 {
            get {
                return ResourceManager.GetString("CreateTokenInstructions_Step3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Copy the new key. 的當地語系化字串。
        /// </summary>
        internal static string CreateTokenInstructions_Step4 {
            get {
                return ResourceManager.GetString("CreateTokenInstructions_Step4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Paste the key into the field above and
        ///press &quot;Register&quot;. 的當地語系化字串。
        /// </summary>
        internal static string CreateTokenInstructions_Step5 {
            get {
                return ResourceManager.GetString("CreateTokenInstructions_Step5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 You can register a key without all permissions, but some
        ///features and modules may fail to function properly.
        ///
        ///At a minimum, &quot;Account&quot; and &quot;Character&quot; permissions
        ///are required. 的當地語系化字串。
        /// </summary>
        internal static string CreateTokenInstructions_Warning {
            get {
                return ResourceManager.GetString("CreateTokenInstructions_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Manage Applications 的當地語系化字串。
        /// </summary>
        internal static string Link_ManageApplications {
            get {
                return ResourceManager.GetString("Link_ManageApplications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Delete Token 的當地語系化字串。
        /// </summary>
        internal static string ManageApiKeys_DeleteToken {
            get {
                return ResourceManager.GetString("ManageApiKeys_DeleteToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Register 的當地語系化字串。
        /// </summary>
        internal static string ManageApiKeys_Register {
            get {
                return ResourceManager.GetString("ManageApiKeys_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Register API Key 的當地語系化字串。
        /// </summary>
        internal static string ManageApiKeys_Title {
            get {
                return ResourceManager.GetString("ManageApiKeys_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Manage API Keys 的當地語系化字串。
        /// </summary>
        internal static string ManageApiKeysSection {
            get {
                return ResourceManager.GetString("ManageApiKeysSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 (no name) 的當地語系化字串。
        /// </summary>
        internal static string Token_NoName {
            get {
                return ResourceManager.GetString("Token_NoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Account Details 的當地語系化字串。
        /// </summary>
        internal static string TokenLoading_AccountDetails {
            get {
                return ResourceManager.GetString("TokenLoading_AccountDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Characters 的當地語系化字串。
        /// </summary>
        internal static string TokenLoading_Characters {
            get {
                return ResourceManager.GetString("TokenLoading_Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Handling response from API... 的當地語系化字串。
        /// </summary>
        internal static string TokenLoading_HandlingResponse {
            get {
                return ResourceManager.GetString("TokenLoading_HandlingResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Loading {0}... 的當地語系化字串。
        /// </summary>
        internal static string TokenLoading_Status {
            get {
                return ResourceManager.GetString("TokenLoading_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Token Info 的當地語系化字串。
        /// </summary>
        internal static string TokenLoading_TokenInfo {
            get {
                return ResourceManager.GetString("TokenLoading_TokenInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Your account display name, ID, home world, and list of guilds. 的當地語系化字串。
        /// </summary>
        internal static string TokenPermissionDescription_Account {
            get {
                return ResourceManager.GetString("TokenPermissionDescription_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Your currently equipped specializations, traits, skills, and equipment for all game modes. 的當地語系化字串。
        /// </summary>
        internal static string TokenPermissionDescription_Builds {
            get {
                return ResourceManager.GetString("TokenPermissionDescription_Builds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Basic information about your characters. 的當地語系化字串。
        /// </summary>
        internal static string TokenPermissionDescription_Characters {
            get {
                return ResourceManager.GetString("TokenPermissionDescription_Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Guilds&apos; rosters, history, and MOTDs for all guilds you are a member of. 的當地語系化字串。
        /// </summary>
        internal static string TokenPermissionDescription_Guilds {
            get {
                return ResourceManager.GetString("TokenPermissionDescription_Guilds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Your account bank, material storage, recipe unlocks, and character inventories. 的當地語系化字串。
        /// </summary>
        internal static string TokenPermissionDescription_Inventories {
            get {
                return ResourceManager.GetString("TokenPermissionDescription_Inventories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Your achievements, dungeon unlock status, mastery point assignments, and general PvE progress. 的當地語系化字串。
        /// </summary>
        internal static string TokenPermissionDescription_Progression {
            get {
                return ResourceManager.GetString("TokenPermissionDescription_Progression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Your PvP stats, match history, reward track progression, and custom arena details. 的當地語系化字串。
        /// </summary>
        internal static string TokenPermissionDescription_Pvp {
            get {
                return ResourceManager.GetString("TokenPermissionDescription_Pvp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Your Trading Post transactions. 的當地語系化字串。
        /// </summary>
        internal static string TokenPermissionDescription_Tradingpost {
            get {
                return ResourceManager.GetString("TokenPermissionDescription_Tradingpost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Your wardrobe unlocks—skins, dyes, minipets, finishers, etc.—and currently equipped skins. 的當地語系化字串。
        /// </summary>
        internal static string TokenPermissionDescription_Unlocks {
            get {
                return ResourceManager.GetString("TokenPermissionDescription_Unlocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Your account&apos;s wallet. 的當地語系化字串。
        /// </summary>
        internal static string TokenPermissionDescription_Wallet {
            get {
                return ResourceManager.GetString("TokenPermissionDescription_Wallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Europe 的當地語系化字串。
        /// </summary>
        internal static string TokenRegion_Europe {
            get {
                return ResourceManager.GetString("TokenRegion_Europe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 France 的當地語系化字串。
        /// </summary>
        internal static string TokenRegion_France {
            get {
                return ResourceManager.GetString("TokenRegion_France", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Germany 的當地語系化字串。
        /// </summary>
        internal static string TokenRegion_Germany {
            get {
                return ResourceManager.GetString("TokenRegion_Germany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 US / North America 的當地語系化字串。
        /// </summary>
        internal static string TokenRegion_NorthAmerica {
            get {
                return ResourceManager.GetString("TokenRegion_NorthAmerica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Spain 的當地語系化字串。
        /// </summary>
        internal static string TokenRegion_Spain {
            get {
                return ResourceManager.GetString("TokenRegion_Spain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Getting account details failed 的當地語系化字串。
        /// </summary>
        internal static string TokenStatus_AccountFailed {
            get {
                return ResourceManager.GetString("TokenStatus_AccountFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Failed to load token. 的當地語系化字串。
        /// </summary>
        internal static string TokenStatus_FailedToLoad {
            get {
                return ResourceManager.GetString("TokenStatus_FailedToLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Invalid token 的當地語系化字串。
        /// </summary>
        internal static string TokenStatus_InvalidToken {
            get {
                return ResourceManager.GetString("TokenStatus_InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Missing required permissions 的當地語系化字串。
        /// </summary>
        internal static string TokenStatus_MissingMinPermission {
            get {
                return ResourceManager.GetString("TokenStatus_MissingMinPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Token missing permissions 的當地語系化字串。
        /// </summary>
        internal static string TokenStatus_PartialPermission {
            get {
                return ResourceManager.GetString("TokenStatus_PartialPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0} ({1}) - Valid token 的當地語系化字串。
        /// </summary>
        internal static string TokenStatus_ValidToken {
            get {
                return ResourceManager.GetString("TokenStatus_ValidToken", resourceCulture);
            }
        }
    }
}
