//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blish_HUD.Strings.GameServices {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ModulesService {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ModulesService() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Blish_HUD.Strings.GameServices.ModulesService", typeof(ModulesService).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Missing required permissions: 的當地語系化字串。
        /// </summary>
        internal static string ApiPermission_MissingRequiredPermissions {
            get {
                return ResourceManager.GetString("ApiPermission_MissingRequiredPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 No permissions requested 的當地語系化字串。
        /// </summary>
        internal static string ApiPermission_NoPermissionsRequested {
            get {
                return ResourceManager.GetString("ApiPermission_NoPermissionsRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Permissions may only be edited, when the module is disabled. 的當地語系化字串。
        /// </summary>
        internal static string ApiPermission_NotEditable {
            get {
                return ResourceManager.GetString("ApiPermission_NotEditable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Optional 的當地語系化字串。
        /// </summary>
        internal static string ApiPermission_Optional {
            get {
                return ResourceManager.GetString("ApiPermission_Optional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 has requested to read from the following APIs 的當地語系化字串。
        /// </summary>
        internal static string ApiPermission_RequestedApiPermissionsInfo {
            get {
                return ResourceManager.GetString("ApiPermission_RequestedApiPermissionsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Required 的當地語系化字串。
        /// </summary>
        internal static string ApiPermission_Required {
            get {
                return ResourceManager.GetString("ApiPermission_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 This module relies on dependencies not currently available: 的當地語系化字串。
        /// </summary>
        internal static string Dependency_MissingDependencies {
            get {
                return ResourceManager.GetString("Dependency_MissingDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 No dependencies 的當地語系化字串。
        /// </summary>
        internal static string Dependency_NoDependencies {
            get {
                return ResourceManager.GetString("Dependency_NoDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 [Not Enabled] 的當地語系化字串。
        /// </summary>
        internal static string Dependency_NotEnabled {
            get {
                return ResourceManager.GetString("Dependency_NotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 [Not Found] 的當地語系化字串。
        /// </summary>
        internal static string Dependency_NotFound {
            get {
                return ResourceManager.GetString("Dependency_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Requires {0} 的當地語系化字串。
        /// </summary>
        internal static string Dependency_RequiresVersion {
            get {
                return ResourceManager.GetString("Dependency_RequiresVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 [Wrong Version] 的當地語系化字串。
        /// </summary>
        internal static string Dependency_WrongVersion {
            get {
                return ResourceManager.GetString("Dependency_WrongVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Manage Modules 的當地語系化字串。
        /// </summary>
        internal static string ManageModulesSection {
            get {
                return ResourceManager.GetString("ManageModulesSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 API Permissions 的當地語系化字串。
        /// </summary>
        internal static string ModuleManagement_ApiPermissions {
            get {
                return ResourceManager.GetString("ModuleManagement_ApiPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Authored by 的當地語系化字串。
        /// </summary>
        internal static string ModuleManagement_AuthoredBy {
            get {
                return ResourceManager.GetString("ModuleManagement_AuthoredBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Clear Permissions 的當地語系化字串。
        /// </summary>
        internal static string ModuleManagement_ClearPermissions {
            get {
                return ResourceManager.GetString("ModuleManagement_ClearPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Dependencies 的當地語系化字串。
        /// </summary>
        internal static string ModuleManagement_Dependencies {
            get {
                return ResourceManager.GetString("ModuleManagement_Dependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Description 的當地語系化字串。
        /// </summary>
        internal static string ModuleManagement_Description {
            get {
                return ResourceManager.GetString("ModuleManagement_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Disable Module 的當地語系化字串。
        /// </summary>
        internal static string ModuleManagement_DisableModule {
            get {
                return ResourceManager.GetString("ModuleManagement_DisableModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Enable Module 的當地語系化字串。
        /// </summary>
        internal static string ModuleManagement_EnableModule {
            get {
                return ResourceManager.GetString("ModuleManagement_EnableModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Ignore Dependency Requirements 的當地語系化字串。
        /// </summary>
        internal static string ModuleManagement_IgnoreDependencyRequirements {
            get {
                return ResourceManager.GetString("ModuleManagement_IgnoreDependencyRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Modify Permissions 的當地語系化字串。
        /// </summary>
        internal static string ModuleManagement_ModifyPermissions {
            get {
                return ResourceManager.GetString("ModuleManagement_ModifyPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Module Settings 的當地語系化字串。
        /// </summary>
        internal static string ModuleManagement_ModuleSettings {
            get {
                return ResourceManager.GetString("ModuleManagement_ModuleSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 View Module Logs 的當地語系化字串。
        /// </summary>
        internal static string ModuleManagement_ViewModuleLogs {
            get {
                return ResourceManager.GetString("ModuleManagement_ViewModuleLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Clear Settings 的當地語系化字串。
        /// </summary>
        internal static string ModuleOption_ClearSettings {
            get {
                return ResourceManager.GetString("ModuleOption_ClearSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Can&apos;t clear settings while the module is enabled. 的當地語系化字串。
        /// </summary>
        internal static string ModuleOption_ClearSettings_DescriptionDisabled {
            get {
                return ResourceManager.GetString("ModuleOption_ClearSettings_DescriptionDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Reset the module settings back to their default. 的當地語系化字串。
        /// </summary>
        internal static string ModuleOption_ClearSettings_DescriptionEnabled {
            get {
                return ResourceManager.GetString("ModuleOption_ClearSettings_DescriptionEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Delete Module 的當地語系化字串。
        /// </summary>
        internal static string ModuleOption_DeleteModule {
            get {
                return ResourceManager.GetString("ModuleOption_DeleteModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Open &apos;{0}&apos; Directory 的當地語系化字串。
        /// </summary>
        internal static string ModuleOption_OpenDir {
            get {
                return ResourceManager.GetString("ModuleOption_OpenDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Settings will show when Module is enabled 的當地語系化字串。
        /// </summary>
        internal static string ModuleSettings_ShownWhenEnabled {
            get {
                return ResourceManager.GetString("ModuleSettings_ShownWhenEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Module Version Is Incompatible 的當地語系化字串。
        /// </summary>
        internal static string ModuleState_Custom_ExplicitlyIncompatible {
            get {
                return ResourceManager.GetString("ModuleState_Custom_ExplicitlyIncompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Disabled 的當地語系化字串。
        /// </summary>
        internal static string ModuleState_Disabled {
            get {
                return ResourceManager.GetString("ModuleState_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Disabling 的當地語系化字串。
        /// </summary>
        internal static string ModuleState_Disabling {
            get {
                return ResourceManager.GetString("ModuleState_Disabling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Enabled 的當地語系化字串。
        /// </summary>
        internal static string ModuleState_Enabled {
            get {
                return ResourceManager.GetString("ModuleState_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Fatal Error 的當地語系化字串。
        /// </summary>
        internal static string ModuleState_FatalError {
            get {
                return ResourceManager.GetString("ModuleState_FatalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Loading 的當地語系化字串。
        /// </summary>
        internal static string ModuleState_Loading {
            get {
                return ResourceManager.GetString("ModuleState_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 You don&apos;t currently have any modules.
        ///Download some modules and place them in the modules folder. 的當地語系化字串。
        /// </summary>
        internal static string NoModules_Info {
            get {
                return ResourceManager.GetString("NoModules_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Open Modules Folder 的當地語系化字串。
        /// </summary>
        internal static string NoModules_OpenFolder {
            get {
                return ResourceManager.GetString("NoModules_OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Installing... 的當地語系化字串。
        /// </summary>
        internal static string PkgInstall_Progress_Installing {
            get {
                return ResourceManager.GetString("PkgInstall_Progress_Installing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Upgrading... 的當地語系化字串。
        /// </summary>
        internal static string PkgInstall_Progress_Upgrading {
            get {
                return ResourceManager.GetString("PkgInstall_Progress_Upgrading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Current Version 的當地語系化字串。
        /// </summary>
        internal static string PkgManagement_CurrentVersion {
            get {
                return ResourceManager.GetString("PkgManagement_CurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Downgrade 的當地語系化字串。
        /// </summary>
        internal static string PkgManagement_Downgrade {
            get {
                return ResourceManager.GetString("PkgManagement_Downgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Install 的當地語系化字串。
        /// </summary>
        internal static string PkgManagement_Install {
            get {
                return ResourceManager.GetString("PkgManagement_Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Preview Release 的當地語系化字串。
        /// </summary>
        internal static string PkgManagement_IsPreview {
            get {
                return ResourceManager.GetString("PkgManagement_IsPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Blish HUD requires a restart before some modules can be re-enabled. 的當地語系化字串。
        /// </summary>
        internal static string PkgManagement_ModulesNeedRestart {
            get {
                return ResourceManager.GetString("PkgManagement_ModulesNeedRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 More Info 的當地語系化字串。
        /// </summary>
        internal static string PkgManagement_MoreInfo {
            get {
                return ResourceManager.GetString("PkgManagement_MoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Checking repository... 的當地語系化字串。
        /// </summary>
        internal static string PkgManagement_Progress_CheckingRepository {
            get {
                return ResourceManager.GetString("PkgManagement_Progress_CheckingRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Failed to pull root from package repo. 的當地語系化字串。
        /// </summary>
        internal static string PkgManagement_Progress_FailedToGetReleases {
            get {
                return ResourceManager.GetString("PkgManagement_Progress_FailedToGetReleases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Failed to get or parse latest repo manifest. 的當地語系化字串。
        /// </summary>
        internal static string PkgManagement_Progress_FailedToReadOrParseRepoManifest {
            get {
                return ResourceManager.GetString("PkgManagement_Progress_FailedToReadOrParseRepoManifest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Getting module list... 的當地語系化字串。
        /// </summary>
        internal static string PkgManagement_Progress_GettingModuleList {
            get {
                return ResourceManager.GetString("PkgManagement_Progress_GettingModuleList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Update 的當地語系化字串。
        /// </summary>
        internal static string PkgManagement_Update {
            get {
                return ResourceManager.GetString("PkgManagement_Update", resourceCulture);
            }
        }
    }
}
