//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blish_HUD.Strings.GameServices {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OverlayService {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OverlayService() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Blish_HUD.Strings.GameServices.OverlayService", typeof(OverlayService).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Join our Discord 的當地語系化字串。
        /// </summary>
        internal static string About_DiscordCallToAction_Button {
            get {
                return ResourceManager.GetString("About_DiscordCallToAction_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  
        ///Need help or just want to
        ///participate in the conversation? 的當地語系化字串。
        /// </summary>
        internal static string About_DiscordCallToAction_Question {
            get {
                return ResourceManager.GetString("About_DiscordCallToAction_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  
        ///The majority of Blish HUD&apos;s feedback, development, and other discussions take place in our 的當地語系化字串。
        /// </summary>
        internal static string About_DiscordCallToAction1 {
            get {
                return ResourceManager.GetString("About_DiscordCallToAction1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Discord 的當地語系化字串。
        /// </summary>
        internal static string About_DiscordCallToAction2 {
            get {
                return ResourceManager.GetString("About_DiscordCallToAction2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  channel.
        ///  的當地語系化字串。
        /// </summary>
        internal static string About_DiscordCallToAction3 {
            get {
                return ResourceManager.GetString("About_DiscordCallToAction3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Update Blish HUD 的當地語系化字串。
        /// </summary>
        internal static string About_UpdateButton {
            get {
                return ResourceManager.GetString("About_UpdateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 An update to Blish HUD v{0} is available! 的當地語系化字串。
        /// </summary>
        internal static string About_UpdateStatus_Available {
            get {
                return ResourceManager.GetString("About_UpdateStatus_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 You are running the latest version of Blish HUD. 的當地語系化字串。
        /// </summary>
        internal static string About_UpdateStatus_Latest {
            get {
                return ResourceManager.GetString("About_UpdateStatus_Latest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ©2010-{0} ArenaNet, LLC. All rights reserved. Guild Wars, Guild Wars 2, Heart of Thorns,
        ///Guild Wars 2: Path of Fire, ArenaNet, NCSOFT, the Interlocking NC Logo, and all associated
        ///logos and designs are trademarks or registered trademarks of NCSOFT Corporation. All other
        ///trademarks are the property of their respective owners. 的當地語系化字串。
        /// </summary>
        internal static string AboutAnetNotice {
            get {
                return ResourceManager.GetString("AboutAnetNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Designed and built with all the love in Tyria by
        ///the Blish HUD team with help from many more! 的當地語系化字串。
        /// </summary>
        internal static string AboutLoveMessage {
            get {
                return ResourceManager.GetString("AboutLoveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 About 的當地語系化字串。
        /// </summary>
        internal static string AboutSection {
            get {
                return ResourceManager.GetString("AboutSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 
        ///
        ///Blish HUD
        ///
        ///MIT License
        ///
        ///Copyright (c) 2022 Dade Lamkins
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy
        ///of this software and associated documentation files (the &quot;Software&quot;), to deal
        ///in the Software without restriction, including without limitation the rights
        ///to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        ///copies of the Software, and to permit persons to whom the Software is
        ///furnished to do so, subject to the following conditions:
        ///
        ///The  [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string AboutThirdPartySoftware {
            get {
                return ResourceManager.GetString("AboutThirdPartySoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Software Licences 的當地語系化字串。
        /// </summary>
        internal static string AboutThirdPartySoftwareHeading {
            get {
                return ResourceManager.GetString("AboutThirdPartySoftwareHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Connected to ArcDPS via bridge plugin. 的當地語系化字串。
        /// </summary>
        internal static string ConnectionStatus_ArcDPSBridge_Connected {
            get {
                return ResourceManager.GetString("ConnectionStatus_ArcDPSBridge_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 No connection received from bridge.
        ///
        ///It might not be installed. 的當地語系化字串。
        /// </summary>
        internal static string ConnectionStatus_ArcDPSBridge_Disconnected {
            get {
                return ResourceManager.GetString("ConnectionStatus_ArcDPSBridge_Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ArcDPS Bridge 的當地語系化字串。
        /// </summary>
        internal static string ConnectionStatus_ArcDPSBridge_Name {
            get {
                return ResourceManager.GetString("ConnectionStatus_ArcDPSBridge_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Connected to MumbleLink with name &apos;{0}&apos;. 的當地語系化字串。
        /// </summary>
        internal static string ConnectionStatus_Mumble_Connected {
            get {
                return ResourceManager.GetString("ConnectionStatus_Mumble_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Unable to connect to MumbleLink with name &apos;{0}&apos;.
        ///
        ///Check what launch arguments were used
        ///to launch both Guild Wars 2 and Blish HUD. 的當地語系化字串。
        /// </summary>
        internal static string ConnectionStatus_Mumble_Disconnected {
            get {
                return ResourceManager.GetString("ConnectionStatus_Mumble_Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 MumbleLink 的當地語系化字串。
        /// </summary>
        internal static string ConnectionStatus_Mumble_Name {
            get {
                return ResourceManager.GetString("ConnectionStatus_Mumble_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Home 的當地語系化字串。
        /// </summary>
        internal static string HomeTab {
            get {
                return ResourceManager.GetString("HomeTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Dynamic HUD 的當地語系化字串。
        /// </summary>
        internal static string OverlayDynamicHUDSection {
            get {
                return ResourceManager.GetString("OverlayDynamicHUDSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Overlay Settings 的當地語系化字串。
        /// </summary>
        internal static string OverlaySettingsSection {
            get {
                return ResourceManager.GetString("OverlaySettingsSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Changes in v{0} 的當地語系化字串。
        /// </summary>
        internal static string SelfUpdate_ChangesInVersion {
            get {
                return ResourceManager.GetString("SelfUpdate_ChangesInVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 New Prerelease Available 的當地語系化字串。
        /// </summary>
        internal static string SelfUpdate_NewPrereleaseAvailable {
            get {
                return ResourceManager.GetString("SelfUpdate_NewPrereleaseAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 New Release Available 的當地語系化字串。
        /// </summary>
        internal static string SelfUpdate_NewUpdateAvailable {
            get {
                return ResourceManager.GetString("SelfUpdate_NewUpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 No Pending Updates 的當地語系化字串。
        /// </summary>
        internal static string SelfUpdate_NoPendingUpdates {
            get {
                return ResourceManager.GetString("SelfUpdate_NoPendingUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Failed to Check for Updates 的當地語系化字串。
        /// </summary>
        internal static string SelfUpdate_PendingUpdatesQueryFailed {
            get {
                return ResourceManager.GetString("SelfUpdate_PendingUpdatesQueryFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Downloading prerelease v{0}... 的當地語系化字串。
        /// </summary>
        internal static string SelfUpdate_Progress_DownloadingPrereleaseArchive {
            get {
                return ResourceManager.GetString("SelfUpdate_Progress_DownloadingPrereleaseArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Downloading release v{0}... 的當地語系化字串。
        /// </summary>
        internal static string SelfUpdate_Progress_DownloadingReleaseArchive {
            get {
                return ResourceManager.GetString("SelfUpdate_Progress_DownloadingReleaseArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Extracting new executable... 的當地語系化字串。
        /// </summary>
        internal static string SelfUpdate_Progress_ExtractingExecutable {
            get {
                return ResourceManager.GetString("SelfUpdate_Progress_ExtractingExecutable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Restarting... 的當地語系化字串。
        /// </summary>
        internal static string SelfUpdate_Progress_Restarting {
            get {
                return ResourceManager.GetString("SelfUpdate_Progress_Restarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Restarting in {0}... 的當地語系化字串。
        /// </summary>
        internal static string SelfUpdate_Progress_RestartingIn {
            get {
                return ResourceManager.GetString("SelfUpdate_Progress_RestartingIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Verifying checksum... 的當地語系化字串。
        /// </summary>
        internal static string SelfUpdate_Progress_VerifyingChecksum {
            get {
                return ResourceManager.GetString("SelfUpdate_Progress_VerifyingChecksum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Update to Prerelease v{0} 的當地語系化字串。
        /// </summary>
        internal static string SelfUpdate_UpdateToPrereleaseMenuStripText {
            get {
                return ResourceManager.GetString("SelfUpdate_UpdateToPrereleaseMenuStripText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Update to Release v{0} 的當地語系化字串。
        /// </summary>
        internal static string SelfUpdate_UpdateToReleaseMenuStripText {
            get {
                return ResourceManager.GetString("SelfUpdate_UpdateToReleaseMenuStripText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Determines the language used when displaying Blish HUD text and when requests are made to the GW2 web API. 的當地語系化字串。
        /// </summary>
        internal static string Setting_AppCulture_Description {
            get {
                return ResourceManager.GetString("Setting_AppCulture_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Application &amp; API Language 的當地語系化字串。
        /// </summary>
        internal static string Setting_AppCulture_DisplayName {
            get {
                return ResourceManager.GetString("Setting_AppCulture_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 This determines the Audio output device used by Blish HUD. The Gw2OutputDevice adjusts itself to whatever GW2 is using. 的當地語系化字串。
        /// </summary>
        internal static string Setting_AudioDevice_Description {
            get {
                return ResourceManager.GetString("Setting_AudioDevice_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  (This setting is temporarily disabled in this version) 的當地語系化字串。
        /// </summary>
        internal static string Setting_AudioDevice_Description_DisabledHint {
            get {
                return ResourceManager.GetString("Setting_AudioDevice_Description_DisabledHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Audio Output Device 的當地語系化字串。
        /// </summary>
        internal static string Setting_AudioDevice_DisplayName {
            get {
                return ResourceManager.GetString("Setting_AudioDevice_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Closes Blish windows when focused and escape key is pressed 的當地語系化字串。
        /// </summary>
        internal static string Setting_CloseWindowOnEscape_Description {
            get {
                return ResourceManager.GetString("Setting_CloseWindowOnEscape_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Close Window on Escape 的當地語系化字串。
        /// </summary>
        internal static string Setting_CloseWindowOnEscape_DisplayName {
            get {
                return ResourceManager.GetString("Setting_CloseWindowOnEscape_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Always Show (Default) 的當地語系化字串。
        /// </summary>
        internal static string Setting_DynamicHUD_AlwaysShow {
            get {
                return ResourceManager.GetString("Setting_DynamicHUD_AlwaysShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Never Show 的當地語系化字串。
        /// </summary>
        internal static string Setting_DynamicHUD_NeverShow {
            get {
                return ResourceManager.GetString("Setting_DynamicHUD_NeverShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Show Only in Combat 的當地語系化字串。
        /// </summary>
        internal static string Setting_DynamicHUD_ShowInCombat {
            get {
                return ResourceManager.GetString("Setting_DynamicHUD_ShowInCombat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Show Only out of Combat 的當地語系化字串。
        /// </summary>
        internal static string Setting_DynamicHUD_ShowPeaceful {
            get {
                return ResourceManager.GetString("Setting_DynamicHUD_ShowPeaceful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Controls visibility during cut scenes and loading screens. 的當地語系化字串。
        /// </summary>
        internal static string Setting_DynamicHUDLoading_Description {
            get {
                return ResourceManager.GetString("Setting_DynamicHUDLoading_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cut Scene / Loading Screen 的當地語系化字串。
        /// </summary>
        internal static string Setting_DynamicHUDLoading_DisplayName {
            get {
                return ResourceManager.GetString("Setting_DynamicHUDLoading_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Controls visibility of the Menu bar located in the upper-left of the screen. 的當地語系化字串。
        /// </summary>
        internal static string Setting_DynamicHUDMenuBar_Description {
            get {
                return ResourceManager.GetString("Setting_DynamicHUDMenuBar_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Menu Bar 的當地語系化字串。
        /// </summary>
        internal static string Setting_DynamicHUDMenuBar_DisplayName {
            get {
                return ResourceManager.GetString("Setting_DynamicHUDMenuBar_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Controls visibility of the windows. 的當地語系化字串。
        /// </summary>
        internal static string Setting_DynamicHUDWindows_Description {
            get {
                return ResourceManager.GetString("Setting_DynamicHUDWindows_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Windows 的當地語系化字串。
        /// </summary>
        internal static string Setting_DynamicHUDWindows_DisplayName {
            get {
                return ResourceManager.GetString("Setting_DynamicHUDWindows_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Hide all of Blish interface for marvelous screenshots 的當地語系化字串。
        /// </summary>
        internal static string Setting_HideInterfaceKeybind_Description {
            get {
                return ResourceManager.GetString("Setting_HideInterfaceKeybind_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Hide interface 的當地語系化字串。
        /// </summary>
        internal static string Setting_HideInterfaceKeybind_DisplayName {
            get {
                return ResourceManager.GetString("Setting_HideInterfaceKeybind_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Used for interacting with the environment.
        ///For the best experience set this to the same key as in the game. 的當地語系化字串。
        /// </summary>
        internal static string Setting_InteractKey_Description {
            get {
                return ResourceManager.GetString("Setting_InteractKey_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Interact 的當地語系化字串。
        /// </summary>
        internal static string Setting_InteractKey_DisplayName {
            get {
                return ResourceManager.GetString("Setting_InteractKey_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 When enabled, Blish HUD will mute itself when the game does not emit any sound either. 的當地語系化字串。
        /// </summary>
        internal static string Setting_MuteIfNoGameAudio_Description {
            get {
                return ResourceManager.GetString("Setting_MuteIfNoGameAudio_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Mute when Game is muted. 的當地語系化字串。
        /// </summary>
        internal static string Setting_MuteIfNoGameAudio_DisplayName {
            get {
                return ResourceManager.GetString("Setting_MuteIfNoGameAudio_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 When enabled, Blish HUD will be shown in the taskbar while running. 的當地語系化字串。
        /// </summary>
        internal static string Setting_ShowInTaskbar_Description {
            get {
                return ResourceManager.GetString("Setting_ShowInTaskbar_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Show in Taskbar 的當地語系化字串。
        /// </summary>
        internal static string Setting_ShowInTaskbar_DisplayName {
            get {
                return ResourceManager.GetString("Setting_ShowInTaskbar_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 If enabled, prerelease versions of both modules and Blish HUD itself become available through the interface.
        ///
        ///WARNING: Prerelease modules or Blish HUD versions may be unstable.  By enabling this feature, you acknowledge that you&apos;d like to be a guinea pig.  Do not use prerelease modules / versions of Blish HUD unless you&apos;re willing to experience crashes, bugs, or other issues. 的當地語系化字串。
        /// </summary>
        internal static string Setting_ShowPreviews_Description {
            get {
                return ResourceManager.GetString("Setting_ShowPreviews_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Preview Releases 的當地語系化字串。
        /// </summary>
        internal static string Setting_ShowPreviews_DisplayName {
            get {
                return ResourceManager.GetString("Setting_ShowPreviews_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  (Disabled because you launched Blish HUD with --startgw2, --pid, -g, or -P) 的當地語系化字串。
        /// </summary>
        internal static string Setting_StayInTray_AppendDisabled {
            get {
                return ResourceManager.GetString("Setting_StayInTray_AppendDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 If true, Blish HUD will automatically minimize when GW2 closes and will continue running until GW2 is launched again.
        ///You can also use the Blish HUD icon in the tray to launch Guild Wars 2. 的當地語系化字串。
        /// </summary>
        internal static string Setting_StayInTray_Description {
            get {
                return ResourceManager.GetString("Setting_StayInTray_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Minimize to tray when Guild Wars 2 Closes. 的當地語系化字串。
        /// </summary>
        internal static string Setting_StayInTray_DisplayName {
            get {
                return ResourceManager.GetString("Setting_StayInTray_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Set keybind to toggle the main window of Blish HUD 的當地語系化字串。
        /// </summary>
        internal static string Setting_ToggleBlishWindowKeybind_Description {
            get {
                return ResourceManager.GetString("Setting_ToggleBlishWindowKeybind_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Toggle Blish HUD window 的當地語系化字串。
        /// </summary>
        internal static string Setting_ToggleBlishWindowKeybind_DisplayName {
            get {
                return ResourceManager.GetString("Setting_ToggleBlishWindowKeybind_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 When enabled, Blish HUD will adjust it&apos;s volume to the game audio. 的當地語系化字串。
        /// </summary>
        internal static string Setting_UseGameVolume_Description {
            get {
                return ResourceManager.GetString("Setting_UseGameVolume_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Use Game Volume 的當地語系化字串。
        /// </summary>
        internal static string Setting_UseGameVolume_DisplayName {
            get {
                return ResourceManager.GetString("Setting_UseGameVolume_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Determines the volume of Blish HUD. Only has an effect when &apos;Use Game Volume&apos; is deactivated. 的當地語系化字串。
        /// </summary>
        internal static string Setting_Volume_Description {
            get {
                return ResourceManager.GetString("Setting_Volume_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Volume 的當地語系化字串。
        /// </summary>
        internal static string Setting_Volume_DisplayName {
            get {
                return ResourceManager.GetString("Setting_Volume_DisplayName", resourceCulture);
            }
        }
    }
}
